name: Publish GH Pages

on:
  workflow_call:
    secrets:
      BOT_SK:
        required: true
<<<<<<< HEAD:.github/workflows/publish_docs.yml
      BOT_ID:
        required: true
=======
>>>>>>> b7ed9ad4d3c69dcb11db0cf93448a0bb16be2f7d:.github/workflows/docs.yml

  workflow_dispatch:

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Generate bot token
        uses: actions/create-github-app-token@v1
        id: bot_app_token
        with:
          app_id: ${{ secrets.BOT_ID}}
          private_key: ${{ secrets.BOT_SK }}

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.bot_app_token.outputs.token }}

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Npm install
        run: npm ci --ignore-scripts

      - name: Build doc
        run: npm run generate:code-docs

      - name: Upload to GitHub pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_html
          artifact_name: docs-artifact

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
<<<<<<< HEAD:.github/workflows/publish_docs.yml
        env:
          GITHUB_TOKEN: ${{ steps.bot_app_token.outputs.token }}
=======
        with:
          token: ${{ secrets.BOT_SK }}
>>>>>>> b7ed9ad4d3c69dcb11db0cf93448a0bb16be2f7d:.github/workflows/docs.yml
